services:
  - type: web
    name: your-frontend-name
    env: static
    staticPublishPath: dist
    buildCommand: npm run build
    # startCommand: npm run dev
    routes:
      - type: rewrite
        source: /.*  
        destination: /index.html
